alt_black: '#803818'
alt_blue: '#2a77c8'
alt_cyan: '#3089c8'
alt_green: '#c87332'
alt_magenta: '#8de7f0'
alt_red: '#cfa761'
alt_white: '#2fa7d2'
alt_yellow: '#0f3dc8'
background: '#0e0e0e'
black: '#182020'
blue: '#8060a0'
cyan: '#5fc9e0'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#d7e0d7'
magenta: '#a0280f'
primary: '#a0280f'
red: '#a02b13'
secondary: '#d7e0d7'
special: '#1444a0'
tertiary: '#a02b13'
white: '#e0d09b'
window_style: normal
yellow: '#1444a0'
