alt_black: '#a89904'
alt_blue: '#c82420'
alt_cyan: '#49c82a'
alt_green: '#5274c8'
alt_magenta: '#e67bc6'
alt_red: '#c81c27'
alt_white: '#c82098'
alt_yellow: '#44dfda'
background: '#0e0e0e'
black: '#040302'
blue: '#a06207'
cyan: '#dae013'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#5bda38'
magenta: '#920da0'
primary: '#920da0'
red: '#2b48a0'
secondary: '#5bda38'
special: '#2aa02c'
tertiary: '#2b48a0'
white: '#e0e0d7'
window_style: normal
yellow: '#2aa02c'
