alt_black: '#588486'
alt_blue: '#adc8be'
alt_cyan: '#79c893'
alt_green: '#8ec8b8'
alt_magenta: '#92c8bb'
alt_red: '#eef3e8'
alt_white: '#99c8b6'
alt_yellow: '#b8c9be'
background: '#0e0e0e'
black: '#18201e'
blue: '#d6dfd2'
cyan: '#ce847e'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#86a59f'
magenta: '#75a094'
primary: '#75a094'
red: '#6da080'
secondary: '#86a59f'
special: '#71a08d'
tertiary: '#6da080'
white: '#72a0a0'
window_style: normal
yellow: '#71a08d'
