alt_black: '#77808b'
alt_blue: '#deeaf0'
alt_cyan: '#969cc8'
alt_green: '#c8692c'
alt_magenta: '#cbd9e0'
alt_red: '#acbac8'
alt_white: '#525dc8'
alt_yellow: '#c8b7bf'
background: '#0e0e0e'
black: '#1c1d20'
blue: '#b2bec6'
cyan: '#a06b12'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#e0b62e'
magenta: '#4963d7'
primary: '#4963d7'
red: '#e0a20a'
secondary: '#e0b62e'
special: '#a0a0a0'
tertiary: '#e0a20a'
white: '#9b93a0'
window_style: normal
yellow: '#a0a0a0'
