alt_black: '#807b7b'
alt_blue: '#d2d2d2'
alt_cyan: '#c88587'
alt_green: '#c86266'
alt_magenta: '#c8c1c1'
alt_red: '#c8c4c4'
alt_white: '#c89396'
alt_yellow: '#c83c43'
background: '#0e0e0e'
black: '#201f1f'
blue: '#a00c12'
cyan: '#a6a5a5'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#a06565'
magenta: '#e0e0e0'
primary: '#e0e0e0'
red: '#a04e50'
secondary: '#a06565'
special: '#a09e9d'
tertiary: '#a04e50'
white: '#a01417'
window_style: normal
yellow: '#a09e9d'
