alt_black: '#c0811e'
alt_blue: '#e7ba6a'
alt_cyan: '#d09035'
alt_green: '#69c897'
alt_magenta: '#c8380a'
alt_red: '#c87018'
alt_white: '#e1af57'
alt_yellow: '#c85114'
background: '#0e0e0e'
black: '#201c13'
blue: '#8ba014'
cyan: '#60a081'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#e0ba74'
magenta: '#e0bf7f'
primary: '#e0bf7f'
red: '#46a06e'
secondary: '#e0ba74'
special: '#daa145'
tertiary: '#46a06e'
white: '#82a02f'
window_style: normal
yellow: '#daa145'
