alt_black: '#c08b1d'
alt_blue: '#c8be8a'
alt_cyan: '#e9e6b4'
alt_green: '#c8a480'
alt_magenta: '#c8140b'
alt_red: '#c81e0e'
alt_white: '#c82310'
alt_yellow: '#c8b487'
background: '#0e0e0e'
black: '#200d03'
blue: '#a0865b'
cyan: '#a0a06a'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#a07067'
magenta: '#a0946b'
primary: '#a0946b'
red: '#e0160a'
secondary: '#a07067'
special: '#e0d82a'
tertiary: '#e0160a'
white: '#a07524'
window_style: normal
yellow: '#e0d82a'
