alt_black: '#c09e64'
alt_blue: '#c89655'
alt_cyan: '#c89e6b'
alt_green: '#f2ebcb'
alt_magenta: '#c85727'
alt_red: '#c89751'
alt_white: '#d69344'
alt_yellow: '#c87031'
background: '#0e0e0e'
black: '#20180f'
blue: '#a05124'
cyan: '#a05731'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#a08060'
magenta: '#a04c1e'
primary: '#a04c1e'
red: '#b86d2b'
secondary: '#a08060'
special: '#a06a3c'
tertiary: '#b86d2b'
white: '#d8782b'
window_style: normal
yellow: '#a06a3c'
