alt_black: '#445680'
alt_blue: '#6c88c8'
alt_cyan: '#c84912'
alt_green: '#f69432'
alt_magenta: '#c8480c'
alt_red: '#e35708'
alt_white: '#6781c8'
alt_yellow: '#c8572b'
background: '#0e0e0e'
black: '#060204'
blue: '#5a70a0'
cyan: '#a0371b'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#2a4aa0'
magenta: '#a0411a'
primary: '#a0411a'
red: '#5f75a0'
secondary: '#2a4aa0'
special: '#ae3b05'
tertiary: '#5f75a0'
white: '#97b4dd'
window_style: normal
yellow: '#ae3b05'
