alt_black: '#805900'
alt_blue: '#c88a0b'
alt_cyan: '#09c809'
alt_green: '#06c806'
alt_magenta: '#d1257a'
alt_red: '#00c800'
alt_white: '#c89b01'
alt_yellow: '#c80413'
background: '#0e0e0e'
black: '#002000'
blue: '#a06025'
cyan: '#a00108'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#a0a0a0'
magenta: '#a07900'
primary: '#a07900'
red: '#00a000'
secondary: '#a0a0a0'
special: '#05a005'
tertiary: '#00a000'
white: '#00a000'
window_style: normal
yellow: '#05a005'
