alt_black: '#80646f'
alt_blue: '#766ac8'
alt_cyan: '#bfc8bd'
alt_green: '#6760c8'
alt_magenta: '#aba8c8'
alt_red: '#a79ac8'
alt_white: '#7e79c8'
alt_yellow: '#c899c8'
background: '#0e0e0e'
black: '#201c13'
blue: '#a08471'
cyan: '#9197a0'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#90a090'
magenta: '#b8a868'
primary: '#b8a868'
red: '#d7e0be'
secondary: '#90a090'
special: '#a08967'
tertiary: '#d7e0be'
white: '#6a67a0'
window_style: normal
yellow: '#a08967'
