alt_black: '#279496'
alt_blue: '#7f56c8'
alt_cyan: '#5a53c8'
alt_green: '#22e4c6'
alt_magenta: '#8196c8'
alt_red: '#c54ac8'
alt_white: '#3c9cc8'
alt_yellow: '#9d4ec8'
background: '#0e0e0e'
black: '#081c20'
blue: '#1dbda6'
cyan: '#4469a0'
font: -*-terminus-*-*-*-*-12-*-*-*-*-*-*-*
fontName: terminus
fontSize: 12
foreground: '#ffffff'
green: '#4e57a0'
magenta: '#576da0'
primary: '#576da0'
red: '#4636a0'
secondary: '#4e57a0'
special: '#7ba8b2'
tertiary: '#4636a0'
white: '#4d4da0'
window_style: normal
yellow: '#7ba8b2'
